FROM archiveproject-web
COPY --chown=app:app inventory/views.py /app/inventory/views.py
COPY --chown=app:app inventory/urls.py /app/inventory/urls.py
COPY --chown=app:app inventory/templates/inventory/base.html /app/inventory/templates/inventory/base.html
COPY --chown=app:app inventory/templates/inventory/member_detail.html /app/inventory/templates/inventory/member_detail.html
COPY --chown=app:app inventory/templates/inventory/personal_item_form.html /app/inventory/templates/inventory/personal_item_form.html
