# Generated by Django 5.2.8 on 2025-12-08 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disposisi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_surat_diterima', models.DateField()),
                ('nomor_agenda', models.IntegerField()),
                ('tanggal_surat', models.DateField()),
                ('nomor_surat', models.CharField(max_length=50)),
                ('pengirim', models.CharField(max_length=50)),
                ('lampiran', models.CharField(max_length=50)),
                ('tujuan', models.CharField(choices=[('DIRUT', 'Direktur Utama'), ('DIR', 'Direktur')], max_length=20)),
                ('tembusan', models.CharField(max_length=50)),
                ('perihal', models.TextField()),
                ('diajukan_kepada', models.CharField(choices=[('DIRUT', 'Direktur Utama'), ('DIR', 'Direktur')], max_length=20)),
                ('waktu_dibuat', models.DateTimeField(auto_now_add=True)),
                ('waktu_diedit', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
