# Generated by Django 5.2.8 on 2025-12-09 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disposisi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='disposisi',
            name='dokumen_surat_masuk',
            field=models.CharField(default='N/A', max_length=100),
        ),
    ]
