# Generated by Django 5.2.8 on 2025-12-09 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disposisi', '0002_disposisi_dokumen_surat_masuk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disposisi',
            name='nomor_agenda',
            field=models.CharField(max_length=20),
        ),
    ]
