# Generated by Django 5.2.8 on 2026-07-07 06:33

import disposisi.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disposisi', '0003_alter_disposisi_nomor_agenda'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disposisi',
            name='diajukan_kepada',
        ),
        migrations.AddField(
            model_name='disposisi',
            name='dokumen_disposisi',
            field=models.FileField(blank=True, null=True, upload_to=disposisi.models.Disposisi.rename_dokumen_disposisi, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])]),
        ),
        migrations.AddField(
            model_name='disposisi',
            name='id_agenda',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='disposisi',
            name='status_pengajuan',
            field=models.CharField(choices=[('DIBUAT', 'Disposisi Telah Dibuat'), ('DIAJUKAN', 'Disposisi Telah Diajukan'), ('DIISI', 'Disposisi Telah Diisi'), ('SELESAI', 'Disposisi Telah Selesai')], default='DIBUAT', max_length=10),
        ),
        migrations.AddField(
            model_name='disposisi',
            name='tujuan_disposisi',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='disposisi',
            name='dokumen_surat_masuk',
            field=models.FileField(upload_to=disposisi.models.Disposisi.rename_dokumen_surat, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='disposisi',
            name='nomor_agenda',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.CreateModel(
            name='DisposisiLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_log', models.CharField(choices=[('DIBUAT', 'Telah Dibuat'), ('DIEDIT', 'Telah Diedit'), ('UPLOAD_DISPOSISI', 'File Telah Di Upload'), ('AJUKAN_DISPOSISI', 'Diajukan'), ('ISI_DISPOSISI', 'Diisi'), ('SELESAI', 'Selesai')], default='DIBUAT', max_length=20)),
                ('keterangan_log', models.TextField(blank=True)),
                ('waktu', models.DateTimeField(auto_now_add=True)),
                ('disposisi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='disposisi.disposisi')),
                ('user_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userlog', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-waktu'],
            },
        ),
    ]
