# Generated by Django 5.2.8 on 2026-02-09 03:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disposisi', '0004_remove_disposisi_diajukan_kepada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disposisi',
            name='dokumen_surat_masuk',
            field=models.FileField(upload_to='disposisi/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])]),
        ),
    ]
