# Generated by Django 5.2.8 on 2026-07-23 04:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disposisi', '0004_remove_disposisi_diajukan_kepada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='disposisi',
            name='isi_disposisi',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='disposisi',
            name='tipe_disposisi',
            field=models.CharField(choices=[('BELUM', 'Metode Belum Dipilih'), ('ONLINE', 'Disposisi Online'), ('OFFLINE', 'Upload Disposisi Fisik (Offline)')], default='BELUM', max_length=10),
        ),
        migrations.AlterField(
            model_name='disposisi',
            name='status_pengajuan',
            field=models.CharField(choices=[('DIBUAT', 'Disposisi Telah Dibuat'), ('DIAJUKAN', 'Disposisi Telah Diajukan'), ('DIISI', 'Disposisi Telah Diisi'), ('DIBAGIKAN', 'Disposisi Telah Dibagikan'), ('SELESAI', 'Disposisi Telah Selesai')], default='DIBUAT', max_length=10),
        ),
        migrations.AlterField(
            model_name='disposisilog',
            name='action_log',
            field=models.CharField(choices=[('DIBUAT', 'Telah Dibuat'), ('DIEDIT', 'Telah Diedit'), ('UPLOAD_DISPOSISI', 'File Telah Di Upload'), ('AJUKAN_DISPOSISI', 'Diajukan'), ('BATAL_PENGAJUAN', 'Pengajuan Dibatalkan'), ('TOLAK_DISPOSISI', 'Pengajuan Ditolak'), ('SETUJUI_DISPOSISI', 'Pengajuan Disetujui'), ('ISI_DISPOSISI', 'Diisi'), ('BAGI_DISPOSISI', 'Dibagi'), ('TERIMA_DISPOSISI', 'Penerima Menyetujui'), ('SELESAI', 'Selesai')], default='DIBUAT', max_length=20),
        ),
        migrations.CreateModel(
            name='DisposisiRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('direktur_utama', 'Direktur Utama'), ('direktur_umum', 'Direktur Umum'), ('kadiv_akuntansi', 'Kepala Divisi Akuntansi'), ('kadiv_keuangan', 'Kepala Divisi Keuangan'), ('kadiv_risiko', 'Kepala Divisi Manajemen Risiko'), ('kadiv_legal_umum', 'Kepala Divisi Legal dan Umum'), ('kadiv_aset', 'Kepala Divisi Aset'), ('kadiv_spi', 'Kepala Divisi SPI')], max_length=30)),
                ('agreed_at', models.DateTimeField(blank=True, null=True)),
                ('disposisi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_recipients', to='disposisi.disposisi')),
            ],
            options={
                'ordering': ['role'],
                'constraints': [models.UniqueConstraint(fields=('disposisi', 'role'), name='unique_disposisi_recipient_role')],
            },
        ),
    ]
