# Generated by Django 5.2.8 on 2026-02-10 02:18

import disposisi.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disposisi', '0005_alter_disposisi_dokumen_surat_masuk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disposisi',
            name='dokumen_surat_masuk',
            field=models.FileField(upload_to=disposisi.models.Disposisi.rename_dokumen_surat, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])]),
        ),
    ]
