# Generated by Django 5.2.8 on 2026-02-10 06:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disposisi', '0006_disposisi_id_agenda_and_more'),
    ]

    # This field is already created by the published 0004 migration.
    operations = []
