# Generated by Django 5.2.8 on 2026-02-20 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disposisi', '0007_disposisi_tujuan_disposisi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disposisi',
            name='id_agenda',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
