# Generated by Django 5.2.8 on 2026-03-03 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disposisi', '0008_change_id_agenda_to_charfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disposisi',
            name='nomor_agenda',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
