# Generated by Django 5.2.8 on 2026-03-09 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disposisi', '0009_nomor_agenda_blank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disposisi',
            name='status_pengajuan',
            field=models.CharField(choices=[('DIBUAT', 'Disposisi Telah Dibuat'), ('DIISI', 'Disposisi Telah Diisi'), ('SELESAI', 'Disposisi Telah Selesai')], default='BELUM', max_length=10),
        ),
    ]
