# Generated by Django 5.2.8 on 2026-03-09 04:20

import disposisi.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disposisi', '0010_add_status_diisi'),
    ]

    # This field is already created by the published 0004 migration.
    operations = []
