# Generated by Django 5.2.8 on 2026-03-11 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disposisi', '0011_add_status_diisi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disposisi',
            name='status_pengajuan',
            field=models.CharField(choices=[('DIBUAT', 'Disposisi Telah Dibuat'), ('DIISI', 'Disposisi Telah Diisi'), ('SELESAI', 'Disposisi Telah Selesai')], default='DIBUAT', max_length=10),
        ),
    ]
