# Generated by Django 5.2.8 on 2026-03-31 07:15

import disposisi.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disposisi', '0012_add_status_diisi'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='disposisi',
            name='dokumen_disposisi',
            field=models.FileField(blank=True, null=True, upload_to=disposisi.models.Disposisi.rename_dokumen_disposisi, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='disposisi',
            name='status_pengajuan',
            field=models.CharField(choices=[('DIBUAT', 'Disposisi Telah Dibuat'), ('DIAJUKAN', 'Disposisi Telah Diajukan'), ('DIISI', 'Disposisi Telah Diisi'), ('SELESAI', 'Disposisi Telah Selesai')], default='DIBUAT', max_length=10),
        ),
    ]
