# Generated by Django 5.2.8 on 2026-07-16 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disposisi', '0013_alter_disposisi_dokumen_disposisi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='disposisi',
            name='tipe_disposisi',
            field=models.CharField(choices=[('ONLINE', 'Disposisi Online'), ('OFFLINE', 'Upload Disposisi Fisik (Offline)')], default='ONLINE', max_length=10),
        ),
        migrations.AlterField(
            model_name='disposisilog',
            name='action_log',
            field=models.CharField(choices=[('DIBUAT', 'Telah Dibuat'), ('DIEDIT', 'Telah Diedit'), ('UPLOAD_DISPOSISI', 'File Telah Di Upload'), ('AJUKAN_DISPOSISI', 'Diajukan'), ('ISI_DISPOSISI', 'Diisi'), ('SELESAI', 'Selesai')], default='DIBUAT', max_length=20),
        ),
    ]
