# Generated by Django 5.2.8 on 2026-07-16 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disposisi', '0014_disposisi_tipe_disposisi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disposisi',
            name='status_pengajuan',
            field=models.CharField(choices=[('DIBUAT', 'Disposisi Telah Dibuat'), ('DIAJUKAN', 'Disposisi Telah Diajukan'), ('DIISI', 'Disposisi Telah Diisi'), ('DIBAGIKAN', 'Disposisi Telah Dibagikan'), ('SELESAI', 'Disposisi Telah Selesai')], default='DIBUAT', max_length=10),
        ),
        migrations.AlterField(
            model_name='disposisilog',
            name='action_log',
            field=models.CharField(choices=[('DIBUAT', 'Telah Dibuat'), ('DIEDIT', 'Telah Diedit'), ('UPLOAD_DISPOSISI', 'File Telah Di Upload'), ('AJUKAN_DISPOSISI', 'Diajukan'), ('ISI_DISPOSISI', 'Diisi'), ('BAGI_DISPOSISI', 'Dibagi'), ('SELESAI', 'Selesai')], default='DIBUAT', max_length=20),
        ),
    ]
