# Generated by Django 5.2.8 on 2026-07-17 10:04

from django.db import migrations, models


def classify_existing_disposisi(apps, schema_editor):
    Disposisi = apps.get_model('disposisi', 'Disposisi')
    existing_online = Disposisi.objects.filter(tipe_disposisi='ONLINE')
    existing_online.filter(
        dokumen_disposisi__isnull=False,
    ).exclude(dokumen_disposisi='').update(tipe_disposisi='OFFLINE')
    existing_online.filter(tipe_disposisi='ONLINE').update(
        tipe_disposisi='BELUM'
    )


def restore_previous_default(apps, schema_editor):
    Disposisi = apps.get_model('disposisi', 'Disposisi')
    Disposisi.objects.filter(tipe_disposisi='BELUM').update(
        tipe_disposisi='ONLINE'
    )


class Migration(migrations.Migration):

    dependencies = [
        ('disposisi', '0015_alter_disposisi_status_pengajuan_and_more'),
    ]

    operations = [
        migrations.RunPython(
            classify_existing_disposisi,
            restore_previous_default,
        ),
        migrations.AlterField(
            model_name='disposisi',
            name='tipe_disposisi',
            field=models.CharField(choices=[('BELUM', 'Metode Belum Dipilih'), ('ONLINE', 'Disposisi Online'), ('OFFLINE', 'Upload Disposisi Fisik (Offline)')], default='BELUM', max_length=10),
        ),
        migrations.AlterField(
            model_name='disposisilog',
            name='action_log',
            field=models.CharField(choices=[('DIBUAT', 'Telah Dibuat'), ('DIEDIT', 'Telah Diedit'), ('UPLOAD_DISPOSISI', 'File Telah Di Upload'), ('AJUKAN_DISPOSISI', 'Diajukan'), ('BATAL_PENGAJUAN', 'Pengajuan Dibatalkan'), ('TOLAK_DISPOSISI', 'Pengajuan Ditolak'), ('SETUJUI_DISPOSISI', 'Pengajuan Disetujui'), ('ISI_DISPOSISI', 'Diisi'), ('BAGI_DISPOSISI', 'Dibagi'), ('SELESAI', 'Selesai')], default='DIBUAT', max_length=20),
        ),
    ]
