# Generated by Django 5.2.8 on 2026-07-20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disposisi', '0016_online_approval_workflow'),
    ]

    operations = [
        migrations.AddField(
            model_name='disposisi',
            name='isi_disposisi',
            field=models.TextField(blank=True, default=''),
        ),
    ]
