# Generated by Django 5.2.16 on 2026-10-01 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disposisi', '0033_rename_direktur_umum_label'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='disposisi',
            index=models.Index(fields=['-tanggal_surat_diterima', '-id'], name='disp_received_pk_idx'),
        ),
        migrations.AddIndex(
            model_name='disposisi',
            index=models.Index(fields=['tipe_disposisi', 'status_pengajuan'], name='disp_type_status_idx'),
        ),
        migrations.AddIndex(
            model_name='disposisi',
            index=models.Index(fields=['tujuan', 'status_pengajuan'], name='disp_target_status_idx'),
        ),
        migrations.AddIndex(
            model_name='disposisi',
            index=models.Index(fields=['status_pengajuan', 'deadline'], name='disp_status_deadline_idx'),
        ),
    ]
