# Generated by Django 5.2.16 on 2026-07-31 03:33

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Kode')),
                ('name', models.CharField(max_length=200, verbose_name='Nama perusahaan')),
                ('company_type', models.CharField(choices=[('holding', 'Perusahaan Induk'), ('subsidiary', 'Anak Perusahaan')], default='subsidiary', max_length=20, verbose_name='Jenis perusahaan')),
                ('registration_number', models.CharField(blank=True, max_length=100, verbose_name='Nomor badan hukum')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('address', models.TextField(blank=True, verbose_name='Alamat')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Perusahaan',
                'verbose_name_plural': 'Perusahaan',
                'ordering': ['company_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CashTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_number', models.CharField(max_length=40, unique=True, verbose_name='Nomor transaksi')),
                ('transaction_date', models.DateField(verbose_name='Tanggal')),
                ('transaction_type', models.CharField(choices=[('income', 'Pemasukan'), ('expense', 'Pengeluaran')], max_length=20, verbose_name='Jenis transaksi')),
                ('category', models.CharField(max_length=100, verbose_name='Kategori')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Jumlah')),
                ('description', models.TextField(verbose_name='Keterangan')),
                ('reference', models.CharField(blank=True, max_length=100, verbose_name='Referensi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_cash_transactions', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_transactions', to='koperasi.company')),
            ],
            options={
                'verbose_name': 'Transaksi kas',
                'verbose_name_plural': 'Transaksi kas',
                'ordering': ['-transaction_date', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_number', models.CharField(max_length=40, unique=True, verbose_name='Nomor pinjaman')),
                ('application_date', models.DateField(verbose_name='Tanggal pengajuan')),
                ('principal_amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Pokok pinjaman')),
                ('interest_rate', models.DecimalField(decimal_places=2, default=0, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Bunga per tahun (%)')),
                ('term_months', models.PositiveIntegerField(verbose_name='Tenor (bulan)')),
                ('purpose', models.TextField(verbose_name='Tujuan pinjaman')),
                ('status', models.CharField(choices=[('draft', 'Draf'), ('submitted', 'Diajukan'), ('approved', 'Disetujui'), ('rejected', 'Ditolak'), ('active', 'Berjalan'), ('paid', 'Lunas'), ('cancelled', 'Dibatalkan')], default='submitted', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('disbursed_date', models.DateField(blank=True, null=True, verbose_name='Tanggal pencairan')),
                ('notes', models.TextField(blank=True, verbose_name='Catatan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_koperasi_loans', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_koperasi_loans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pinjaman',
                'verbose_name_plural': 'Pinjaman',
                'ordering': ['-application_date', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='LoanInstallment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_number', models.CharField(max_length=40, unique=True, verbose_name='Nomor pembayaran')),
                ('payment_date', models.DateField(verbose_name='Tanggal pembayaran')),
                ('principal_amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Angsuran pokok')),
                ('interest_amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Bunga')),
                ('penalty_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Denda')),
                ('reference', models.CharField(blank=True, max_length=100, verbose_name='Referensi')),
                ('notes', models.TextField(blank=True, verbose_name='Catatan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='installments', to='koperasi.loan')),
                ('received_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='received_loan_installments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Angsuran pinjaman',
                'verbose_name_plural': 'Angsuran pinjaman',
                'ordering': ['-payment_date', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_number', models.CharField(max_length=30, unique=True, verbose_name='Nomor anggota')),
                ('employee_number', models.CharField(blank=True, max_length=50, verbose_name='NIP/NIK')),
                ('full_name', models.CharField(max_length=200, verbose_name='Nama lengkap')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('address', models.TextField(blank=True, verbose_name='Alamat')),
                ('join_date', models.DateField(verbose_name='Tanggal bergabung')),
                ('status', models.CharField(choices=[('active', 'Aktif'), ('inactive', 'Tidak Aktif'), ('resigned', 'Keluar')], default='active', max_length=20)),
                ('mandatory_saving_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Simpanan wajib bulanan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='members', to='koperasi.company')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='koperasi_member', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Anggota',
                'verbose_name_plural': 'Anggota',
                'ordering': ['full_name'],
            },
        ),
        migrations.AddField(
            model_name='loan',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loans', to='koperasi.member'),
        ),
        migrations.CreateModel(
            name='SavingTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_number', models.CharField(max_length=40, unique=True, verbose_name='Nomor transaksi')),
                ('saving_type', models.CharField(choices=[('principal', 'Simpanan Pokok'), ('mandatory', 'Simpanan Wajib'), ('voluntary', 'Simpanan Sukarela')], max_length=20, verbose_name='Jenis simpanan')),
                ('direction', models.CharField(choices=[('deposit', 'Setoran'), ('withdrawal', 'Penarikan')], max_length=20, verbose_name='Jenis transaksi')),
                ('transaction_date', models.DateField(verbose_name='Tanggal')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Jumlah')),
                ('reference', models.CharField(blank=True, max_length=100, verbose_name='Referensi')),
                ('notes', models.TextField(blank=True, verbose_name='Catatan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_saving_transactions', to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='saving_transactions', to='koperasi.member')),
            ],
            options={
                'verbose_name': 'Transaksi simpanan',
                'verbose_name_plural': 'Transaksi simpanan',
                'ordering': ['-transaction_date', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='KoperasiAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Administrator Koperasi'), ('manager', 'Manajer Koperasi'), ('finance', 'Keuangan'), ('officer', 'Petugas'), ('auditor', 'Auditor'), ('viewer', 'Pembaca')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(blank=True, help_text='Kosongkan untuk akses ke seluruh perusahaan.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accesses', to='koperasi.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='koperasi_accesses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Hak akses Koperasi',
                'verbose_name_plural': 'Hak akses Koperasi',
                'constraints': [models.UniqueConstraint(fields=('user', 'company'), name='unique_koperasi_user_company')],
            },
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['company', 'status'], name='member_company_status_idx'),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['member', 'status'], name='loan_member_status_idx'),
        ),
        migrations.AddIndex(
            model_name='savingtransaction',
            index=models.Index(fields=['member', 'transaction_date'], name='saving_member_date_idx'),
        ),
    ]
