# Generated by Django 5.2.16 on 2026-07-31 03:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('koperasi', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='koperasiaccess',
            name='unique_koperasi_user_company',
        ),
        migrations.AddConstraint(
            model_name='koperasiaccess',
            constraint=models.UniqueConstraint(fields=('user', 'company'), name='unique_koperasi_user_company', nulls_distinct=False),
        ),
    ]
