# Generated by Django 5.2.16 on 2026-10-01 06:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('koperasi', '0007_remove_invalid_access_roles'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='businesstransaction',
            index=models.Index(fields=['company', 'status', 'transaction_date'], name='business_company_date_idx'),
        ),
        migrations.AddIndex(
            model_name='cashtransaction',
            index=models.Index(fields=['company', 'unit', 'transaction_date'], name='cash_company_unit_date_idx'),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['status', 'disbursed_date'], name='loan_status_disbursed_idx'),
        ),
        migrations.AddIndex(
            model_name='loaninstallment',
            index=models.Index(fields=['loan', 'payment_date'], name='installment_loan_date_idx'),
        ),
        migrations.AddIndex(
            model_name='savingtransaction',
            index=models.Index(fields=['transaction_date', 'direction'], name='saving_date_direction_idx'),
        ),
    ]
