# Generated by Django 5.2.8 on 2026-07-23 08:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_director_usernames'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_username', models.CharField(blank=True, max_length=150)),
                ('category', models.CharField(choices=[('AUTH', 'Authentication'), ('DISPOSISI', 'Disposisi'), ('ACCOUNT', 'Account'), ('SYSTEM', 'System')], max_length=20)),
                ('action', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True)),
                ('target_type', models.CharField(blank=True, max_length=100)),
                ('target_id', models.CharField(blank=True, max_length=64)),
                ('target_label', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=512)),
                ('success', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
                'indexes': [models.Index(fields=['created_at'], name='activity_created_idx'), models.Index(fields=['actor', 'created_at'], name='activity_actor_idx'), models.Index(fields=['category', 'action'], name='activity_action_idx')],
            },
        ),
    ]
