# Generated by Django 5.2.16 on 2026-07-31 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_fill_empty_user_emails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='category',
            field=models.CharField(choices=[('AUTH', 'Authentication'), ('DISPOSISI', 'Disposisi'), ('ACCOUNT', 'Account'), ('SYSTEM', 'System'), ('KOPERASI', 'Koperasi')], max_length=20),
        ),
    ]
