# Generated by Django 5.2.16 on 2026-07-31 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_activitylog_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('sekretaris', 'Sekretaris'), ('kadiv', 'Kepala Divisi'), ('direktur', 'Direktur'), ('direktur_utama', 'Direktur Utama'), ('direktur_umum', 'Direktur Umum'), ('kadiv_akuntansi', 'Kepala Divisi Akuntansi'), ('kadiv_keuangan', 'Kepala Divisi Keuangan'), ('kadiv_risiko', 'Kepala Divisi Manajemen Risiko'), ('kadiv_legal_umum', 'Kepala Divisi Legal dan Umum'), ('kadiv_aset', 'Kepala Divisi Aset'), ('kadiv_spi', 'Kepala Divisi SPI'), ('akuntan', 'Akuntan')], max_length=30),
        ),
    ]
