# Generated by Django 5.2.8 on 2026-09-29 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_optional_received_date_and_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='category',
            field=models.CharField(choices=[('computer', 'Komputer'), ('laptop', 'Laptop'), ('peripheral', 'Periferal IT (Keyboard, Mouse, Monitor)'), ('component', 'Komponen Hardware'), ('network', 'Perangkat Jaringan'), ('software', 'Software / Lisensi'), ('hardware', 'Perangkat Keras Lainnya'), ('furniture', 'Furnitur'), ('vehicle', 'Kendaraan'), ('tool', 'Peralatan Kerja'), ('office', 'Perlengkapan Kantor'), ('other', 'Lainnya')], max_length=20, verbose_name='Kategori'),
        ),
    ]
